NAME = libft.a
CC = cc
CFLAGS = -Wall -Wextra -Werror 
MANDATORY_SRC = ft_isalpha.c\
				ft_isdigit.c\
				ft_isalnum.c\
				ft_isascii.c\
				ft_isprint.c\
				ft_strlen.c\
				ft_memset.c\
				ft_bzero.c\
				ft_memcpy.c\
				ft_memmove.c\
				ft_strlcpy.c\
				ft_strlcat.c\
				ft_toupper.c\
				ft_tolower.c\
				ft_strchr.c\
				ft_strrchr.c\
				ft_strncmp.c\
				ft_memchr.c\
				ft_memcmp.c\
				ft_strnstr.c\
				ft_atoi.c\
				ft_calloc.c\
				ft_strdup.c\
				ft_substr.c\
				ft_strjoin.c\
				ft_strtrim.c\
				ft_split.c\
				ft_strcmp.c \
				ft_itoa.c\
				ft_strmapi.c\
				ft_striteri.c\
				ft_putchar_fd.c\
				ft_putstr_fd.c\
				ft_putendl_fd.c\
				ft_putnbr_fd.c\
				get_next_line.c\
				get_next_line_utils.c\
				ft_printf.c \
				ft_decimal_to_hex.c \
				ft_puthex.c \
				ft_putnbr.c \
				ft_putubr.c \
				ft_safe_write.c \
				handle_char.c \
				handle_format.c \
				handle_hex.c \
				handle_integer.c \
				handle_percent.c \
				handle_pointer.c \
				handle_string.c \
				handle_unsigned.c 
				
OFILES = $(MANDATORY_SRC:.c=.o)

all : $(NAME)

$(NAME) : $(OFILES)
	ar rcs $(NAME) $(OFILES)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OFILES)

fclean: clean
	rm -f $(NAME)
	
re: fclean all

.PHONY: all clean fclean re
.SECONDARY: $(OFILES)
